"use client"
import React from 'react';

const TermsConditions: React.FC = () => {
  return (
    <div className="w-full min-h-screen text-white p-8 laptop:p-16 relative">
      <div className="absolute inset-0 z-10 h-full w-full bg-[#0E0F0C] bg-[linear-gradient(to_right,#B0E681_1px,transparent_1px),linear-gradient(to_bottom,#B0E681_1px,transparent_1px)] bg-[size:34px_34px] opacity-5"></div>
      <div className="max-w-4xl mx-auto relative z-[100]">
        <h1 className="text-4xl laptop:text-6xl font-nohemi400 mb-8 text-[#b0e681]">Terms and Conditions</h1>
        
        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">1. Introduction</h2>
        <p className="mb-8 opacity-80">
          Welcome to Tribes – a decentralized platform that empowers blockchain communities by uniting governance, events, and tokenized rewards. By accessing or using Tribes, you agree to be bound by these Terms and Conditions (the &ldquo;Terms&rdquo;). If you disagree with any part of these Terms, please do not use the platform.
        </p>
        
        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">2. Key Definitions</h2>
        <p className="mb-8 opacity-80">
          Platform: The Tribes ecosystem including its web interface, mobile applications, smart contracts, and any related services.<br />
          User: Any individual or entity who accesses or uses the platform.<br />
          Tribe: A community or group created within the platform, often organized around specific projects, interests, or governance structures.<br />
          Content: Any data, text, images, videos, or other digital material submitted or generated by users.<br />
          Token-Gated Access: A mechanism requiring users to hold specified tokens or NFTs to access certain features or communities.<br />
          Smart Contracts: Self-executing contracts with the terms of the agreement directly written into code on the blockchain.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">3. Eligibility and User Responsibilities</h2>
        <p className="mb-8 opacity-80">
          Eligibility: By using Tribes, you represent that you are of legal age in your jurisdiction or have obtained necessary consent to enter into these Terms.<br />
          Accuracy of Information: You agree to provide accurate and complete information when interacting with the platform.<br />
          Wallet Responsibility: Users are solely responsible for safeguarding their private keys and wallet credentials. Tribes is non-custodial and does not manage or recover lost credentials or funds.<br />
          Compliance: You agree to abide by all applicable laws and regulations when using the platform.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">4. Decentralized Nature & On-Chain Immutability</h2>
        <p className="mb-8 opacity-80">
          Immutable Records: Content and transactions on Tribes are recorded on-chain. Once published, content cannot be easily altered or deleted.<br />
          User Responsibility: You are fully responsible for any content you post. Tribes does not actively moderate or remove content unless legally compelled to do so.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">5. User-Generated Content and Moderation</h2>
        <p className="mb-8 opacity-80">
          Content Ownership: You retain ownership of your content. However, by posting on Tribes, you grant the platform a non-exclusive, worldwide, royalty-free license to use, display, and distribute your content for the purpose of operating the platform.<br />
          Minimal Moderation: Tribes operates on a decentralized model with limited moderation. Users are solely responsible for the content they share within their tribe or community. Each Tribe may implement its own rules, but Tribes as a platform will not be held responsible for user-generated content.<br />
          Content Removal: While we reserve the right to remove or restrict access to content that violates applicable laws or these Terms, such actions are at our sole discretion and may be limited given the immutable nature of blockchain records.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">6. Token-Gated Access, Smart Contracts & Financial Transactions</h2>
        <p className="mb-8 opacity-80">
          Non-Custodial Transactions: All transactions, including those related to governance, events, and rewards, are executed via blockchain-based smart contracts.<br />
          No Reversals: Blockchain transactions are irreversible. Ensure that you double-check transaction details before confirmation.<br />
          Financial Risk: You acknowledge that interactions with blockchain networks carry inherent risks such as gas fees, network delays, or transaction failures. Tribes is not liable for such risks.<br />
          No Guarantees on Smart Contract Performance: While our smart contracts are audited and designed for security, they may still be subject to vulnerabilities or bugs.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">7. Intellectual Property Rights</h2>
        <p className="mb-8 opacity-80">
          Platform Content: All intellectual property rights in the Tribes platform (excluding user-generated content) are owned by Tribes or its licensors.<br />
          User Content: You grant Tribes permission to use your content as necessary to operate the platform, while retaining your own copyright or intellectual property rights.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">8. Disclaimers & Limitation of Liability</h2>
        <p className="mb-8 opacity-80">
          &ldquo;As Is&rdquo; Basis: The platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, whether express or implied.<br />
          No Liability for User Content: Tribes is not responsible for user-generated content. All risks associated with content posted by users lie with the respective user.<br />
          Blockchain and Network Risks: Tribes is not liable for any losses, damages, or delays caused by blockchain network issues, smart contract vulnerabilities, or other technical failures beyond our control.<br />
          No Endorsement: The platform does not endorse or verify any content or transactions and is not liable for any disputes that arise among users or communities.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">9. Indemnification</h2>
        <p className="mb-8 opacity-80">
          You agree to indemnify and hold harmless Tribes, its affiliates, officers, and employees from any claims, losses, liabilities, and expenses (including legal fees) arising out of your use of the platform or violation of these Terms.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">10. Governing Law and Dispute Resolution</h2>
        <p className="mb-8 opacity-80">
          Decentralized Jurisdiction: Given the global and decentralized nature of Tribes, no single jurisdiction exclusively governs these Terms.<br />
          User Responsibility: Users must comply with the laws applicable in their own jurisdictions.<br />
          Dispute Resolution: Any disputes arising under these Terms shall be resolved in accordance with the decentralized governance structures of your respective Tribe or through arbitration if necessary.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">11. Changes to Terms</h2>
        <p className="mb-8 opacity-80">
          Tribes reserves the right to modify or update these Terms at any time. Updated Terms will be posted on the platform, and continued use of the platform after such changes will constitute your acceptance of the revised Terms.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">12. Termination and Suspension</h2>
        <p className="mb-8 opacity-80">
          Platform Access: Tribes reserves the right to suspend or terminate your access to the platform if you violate these Terms or engage in illegal or harmful activities.<br />
          On-Chain Data: Due to the immutable nature of blockchain, termination may not remove content already recorded on-chain.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">13. Third-Party Links and Services</h2>
        <p className="mb-8 opacity-80">
          The platform may contain links to third-party websites or services that are not controlled or maintained by Tribes. We are not responsible for the content, privacy practices, or actions of these third parties.
        </p>

        <h2 className="text-2xl laptop:text-4xl font-nohemi300 mb-4">14. Contact Information</h2>
        <p className="opacity-80">
          If you have any questions or concerns about these Terms, please contact us through our official channels: hello@astrix.live
        </p>

        <p className="opacity-80">
          By using Tribes, you acknowledge that you have read, understood, and agreed to these Terms and Conditions.
        </p>
      </div>
    </div>
  );
};

export default TermsConditions; 